### ISSUE TITLE
SOUP Additional Steps Inquiry

### ISSUE THREAD

**Issue by Sloofy** [MysticMoonlight/EnhancedMod#1]
hi i came across this because i was looking for a well-compiled list of tf2 mods.

I was looking at the [TF2: Enhanced mods list](https://github.com/MysticMoonlight/EnhancedMod/blob/main/tf2e/README.md), and I found that there are additional steps listed for SOUP. I'm not sure what these steps are doing, as SOUP bundles Community HUD Fixes already. Actually, it bundles the Community version of HUD Fixes, which includes a few bonus mod additions. Either way, though, it seems like the steps are redundant given that you're doing exactly what the main download is doing.

Just wanted to know what's going on with that so that if I am doing something wrong with SOUP, I can patch that up for SOUP v1.8 and have saner defaults instead of having people jump through extra hoops. For the record, not meaning to be provocative with all that I said just now. I did genuinely get a bit confused to what this meant.

Otherwise, I do plan to remove the hudplayerclass.res requirement because it turns out that this did nothing and only confused people. You only need to drag and drop the SOUP files into whatever HUD you're using. Make sure to update your documentation for this step, if anything. I'll be updating this for SOUP v1.8 when that comes out.

aightio cheers lmk if you want me to elaborate further

**Comment by RoonMoonlight** [comment]
> hi i came across this because i was looking for a well-compiled list of tf2 mods.
> 
> I was looking at the [TF2: Enhanced mods list](https://github.com/MysticMoonlight/EnhancedMod/blob/main/tf2e/README.md), and I found that there are additional steps listed for SOUP. I'm not sure what these steps are doing, as SOUP bundles Community HUD Fixes already. Actually, it bundles the Community version of HUD Fixes, which includes a few bonus mod additions. Either way, though, it seems like the steps are redundant given that you're doing exactly what the main download is doing.
> 
> Just wanted to know what's going on with that so that if I am doing something wrong with SOUP, I can patch that up for SOUP v1.8 and have saner defaults instead of having people jump through extra hoops. For the record, not meaning to be provocative with all that I said just now. I did genuinely get a bit confused to what this meant.
> 
> Otherwise, I do plan to remove the hudplayerclass.res requirement because it turns out that this did nothing and only confused people. You only need to drag and drop the SOUP files into whatever HUD you're using. Make sure to update your documentation for this step, if anything. I'll be updating this for SOUP v1.8 when that comes out.
> 
> aightio cheers lmk if you want me to elaborate further

Hi there, in case of Community HUD Fixes being outdated due to new upstream release (Especially when SOUP have outdated version and in case Sloofy cannot update the mod in time) I've left this optional steps

Yeah it makes very confusing so I will remove it soon!

**Comment by Sloofy** [comment]
hi i am sloofy. i made soup.

I'll try to keep HUD Fixes updated as often as I can. Currently, updating HUD Fixes in SOUP has been on hold as I prepare a few more art assets to coincide with the release of the next SOUP update. But once I do make SOUP v1.8, then you'll see lots of tinier patches updated to the latest GitHub commit of HUD Fixes, which CriticalFlaw tends to leave an outdated version of their mod on GameBanana.

**Comment by Sloofy** [comment]
On an aside, I like your mods list. Been referencing it since last night and it's a good handy compiled list of things.

**Comment by RoonMoonlight** [comment]
> hi i am sloofy. i made soup.
> 
> I'll try to keep HUD Fixes updated as often as I can. Currently, updating HUD Fixes in SOUP has been on hold as I prepare a few more art assets to coincide with the release of the next SOUP update. But once I do make SOUP v1.8, then you'll see lots of tinier patches updated to the latest GitHub commit of HUD Fixes, which CriticalFlaw tends to leave an outdated version of their mod on GameBanana.

Yeah I saw your mods on GameBanana, I really loved your mods as always! (And I already know that you are the author of SOUP so that's fine)

> On an aside, I like your mods list. Been referencing it since last night and it's a good handy compiled list of things.

Aww thank you! I'm glad you loved this mod list!

P.S. Sorry I was on the work since it is afternoon for me, I will work on the next minor fixes (Which also resolves this issue) as soon as possible!

**Comment by Sloofy** [comment]
> (And I already know that you are the author of SOUP so that's fine)
Rightio, just wanted to check. I was wondering if you missed my username because you were referring to me by my name in the original reply, which confused me a bit. I get confused often. It doesn't help when I solve math problems. I digress. Anyways, cheers!

> P.S. Sorry I was on the work since it is afternoon for me, I will work on the next minor fixes (Which also resolves this issue) as soon as possible!
I'll just go ahead and make a pull request of the steps I'm removing from SOUP v1.8 for you if you don't mind. Merge that whenever you feel like it (also, make sure to take things easy with work).

**Comment by RoonMoonlight** [comment]
I've already released the update for Team Fortress 2: Enhanced, but thank you for contribution!
