### ISSUE TITLE
PAYDAY 2 Linux Mod Compatibility

### ISSUE THREAD

**Issue by Sloofy** [MysticMoonlight/EnhancedMod#10]
This is more of a correction, less of a suggestion.

Being on Linux, I don't exactly understand why the PAYDAY 2 list was marked as incompatible on Linux? I've been modding that game for years now, going as far back as 2017 - I say this having used Proton to run the game. In fact, I've got a fairly extensive mod list on hand. 

It's a minor thing, really. And I'm not discrediting your personal experience if you found it didn't work, because the fact that this game runs at all is nothing short of a stroke of luck. However, big emphasis on running it through Proton and mods should work, as some people are reporting on the [ProtonDB page](https://www.protondb.com/app/218620). I would appreciate it if further research could be done here to relist the modpack in the future.

**Comment by RoonMoonlight** [comment]
> This is more of a correction, less of a suggestion.
> 
> Being on Linux, I don't exactly understand why the PAYDAY 2 list was marked as incompatible on Linux? I've been modding that game for years now, going as far back as 2017 - I say this having used Proton to run the game. In fact, I've got a fairly extensive mod list on hand.
> 
> It's a minor thing, really. And I'm not discrediting your personal experience if you found it didn't work, because the fact that this game runs at all is nothing short of a stroke of luck. However, big emphasis on running it through Proton and mods should work, as some people are reporting on the [ProtonDB page](https://www.protondb.com/app/218620). I would appreciate it if further research could be done here to relist the modpack in the future.

Because I couldn't be able to test it myself on Linux Proton (I didn't expected that BLT mod would work well on Proton version because of being unstable on most Windows games)

I will correct it later, thanks for the info

**Comment by RoonMoonlight** [comment]
Fixed
https://github.com/MysticMoonlight/PAYDAY2-HF/commit/2d247073798c3eaa36f6992a9aa7a574f9d204b0

Closing issue #10
