### ISSUE TITLE
[Cosmos] Remove Jumpscare

### ISSUE THREAD

**Issue by RoonMoonlight** [MysticMoonlight/EnhancedMod#13]
Add a mod which removes the Jumpscares including Elder Guardian. This helps you get rid of being annoyed by Elder Guardian covering your screen.

P.S. The Elder Guardian effect sound and debuffs will not have any changes.

**Comment by Lorenmod** [comment]
Kindly Live chat cosmos Agent on live chat support https://cosmossnetwork.com if you have issue or concerns

**Comment by RoonMoonlight** [comment]
Please do not post any advertisement in the issue tracker. Stay on the topic please.
