### ISSUE TITLE
TF2: Tweaked Stamp Background Obsolete

### ISSUE THREAD

**Issue by Sloofy** [MysticMoonlight/EnhancedMod#8]
<!--
----- Note Starts here -----
Please note that we only accept issues related to Enhanced Mod series! Any modpacks that are outside of EnhancedMod should be reported on appropriate place, not here.

Modpacks that includes on Enhanced Mod are:
* Half-Life 2: Enhanced
* Team Fortress 2: Enhanced
* Black Mesa: Enhanced
* Half-Life 2: Re;Enhanced (Not Released)
* Obsidian Conflict: Enhanced (Not Released)
* PAYDAY 2: Enhanced
* Euro Truck Simulator 2: Enhanced
* American Truck Simulator: Enhanced
* Stardew Valley: Wildlife
* Minecraft: Cosmos
* Left 4 Dead 2: Revengeance Reborn (Testing)
* World of Tanks: Great Tank Battle
* World of Warships: Great Warship Battle

Please include more information if possible, so we can help you fix the issue faster ;)
----- Note Ends here -----
--!>

**Which mod is causing error?**
Tweaked Stamp Background

**Please describe explanation about the issues you have.**
After I emailed Valve with the fix, they have since added it in the game. You don't need it anymore.

**Screenshots or videos (If possible)**
N/A, but I can provide screenshots to the Valve email and the changelog patch if required. Former I don't want to share so eagerly, but the latter is on the mod page.

**Which modpack are you using?**
TF2 Enhanced

**What operating system are you using? (e.g. Windows, macOS, Linux)**
Fedora 36 KDE

**Please share additional information related to this issue, if you have any.**
N/A

**Comment by RoonMoonlight** [comment]
> **Which mod is causing error?**
> Tweaked Stamp Background
> 
> **Please describe explanation about the issues you have.**
> After I emailed Valve with the fix, they have since added it in the game. You don't need it anymore.
> 
> **Screenshots or videos (If possible)**
> N/A, but I can provide screenshots to the Valve email and the changelog patch if required. Former I don't want to share so eagerly, but the latter is on the mod page.
> 
> **Which modpack are you using?**
> TF2 Enhanced
> 
> **What operating system are you using? (e.g. Windows, macOS, Linux)**
> Fedora 36 KDE
> 
> **Please share additional information related to this issue, if you have any.**
> N/A

Will be removed on next minor update, thanks for info!

Glad to hear that Valve is working on a fix

**Comment by Sloofy** [comment]
The fix has been in the game since March 2022. They never wrote it on the blog, but the TF2 wiki does state they changed the file with the appropriate patch.

**Comment by RoonMoonlight** [comment]
> The fix has been in the game since March 2022. They never wrote it on the blog, but the [TF2 wiki does state they changed the file with the appropriate patch](https://wiki.teamfortress.com/wiki/March_30,_2022_Patch) alongside my other mod Better Class Portraits.

Okay I pushed the fix right now, but they are incomplete because it is too late time for me... Good night and thank you for reporting issue! Closing #8
